joint_names:
- hip_L_Joint
- hip_R_Joint
- thigh_L_Joint
- thigh_R_Joint
- knee_L_Joint
- knee_R_Joint
- wheel_L_Joint
- wheel_R_Joint
joint_indices:
- 0
- 1
- 2
- 3
- 4
- 5
wheel_indices:
- 6
- 7
num_joints: 8
can_channels:
- can0
- can1
motor_bus_index:
- 0
- 1
- 0
- 1
- 0
- 1
- 0
- 1
motor_node_ids:
- 1
- 2
- 3
- 4
- 5
- 6
- 7
- 8
motor_torque_constant_nm_per_amp:
- 0.2616
- 0.2616
- 0.2616
- 0.2616
- 0.2616
- 0.2616
- 0.2478
- 0.2478
motor_gear_ratio:
- 1
- 1
- 1
- 1
- 2
- 2
- 1
- 1
motor_direction:
- 1
- 1
- 1
- 1
- 1
- 1
- 1
- 1
wheel_radius: 0.07275
nsc_urdf_path: null
nsc_leg_proportional_gain:
- 30.0
- 30.0
- 30.0
- 30.0
- 30.0
- 30.0
- 0.0
- 0.0
nsc_leg_derivative_gain:
- 6.0
- 6.0
- 6.0
- 6.0
- 6.0
- 6.0
- 0.0
- 0.0
nsc_num_traj_points: 1000
nsc_wheel_outer_proportional_gain: 0.02
nsc_wheel_outer_derivative_gain: 0.02
nsc_wheel_inner_proportional_gain: 6.0
nsc_wheel_inner_derivative_gain: 0.6
nsc_theta_cmd_limit: 5.0
policy_mode: movable
policy_checkpoint_path: src/goat_control/checkpoint/stand.onnx
policy_device: cpu
policy_command_vx_limit: 0.1
policy_command_wz_limit: 0.1
policy_command_vx_step: 0.01
policy_command_wz_step: 0.01
policy_command_joint_step: 10.0
policy_decimation: 2.0
policy_fixed:
  observation_info:
    joint_pos: 6
    joint_vel: 6
    previous_action: 6
    joint_command: 6
  action_scale_factor:
  - 0.5
  - 0.5
  - 0.5
  - 0.5
  - 0.5
  - 0.5
  natural_joint_position:
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
policy_movable:
  observation_info:
    base_ang_vel: 3
    base_quat: 4
    base_command: 3
    joint_pos: 6
    joint_vel: 8
    previous_action: 8
  action_scale_factor:
  - 0.5
  - 0.5
  - 0.5
  - 0.5
  - 0.5
  - 0.5
  - 5.0
  - 5.0
  natural_joint_position:
  - 0.0
  - 0.0
  - 0.738
  - -0.738
  - 1.462
  - -1.462
  - 0.0
  - 0.0
policy_leg_proportional_gain:
- 3.0
- 3.0
- 3.0
- 3.0
- 3.0
- 3.0
policy_leg_derivative_gain:
- 0.5
- 0.5
- 0.5
- 0.5
- 0.5
- 0.5
policy_wheel_proportional_gain:
- 0.05
- 0.05
max_torque_per_joint:
- 4.5
- 4.5
- 4.5
- 4.5
- 9.0
- 9.0
- 2.5
- 2.5
joint_pos_limit:
- -1.22173
- 0.750492
- -0.750492
- 1.22173
- -0.261799
- 2.05949
- -2.05949
- 0.261799
- -0.262
- 2.2253
- -2.2253
- 0.262
- -.inf
- .inf
- -.inf
- .inf
joint_pos_soft_limit_coeff: 0.95
joint_vel_estop_threshold: 4.0
motor_current_amp_per_lsb: 0.01611328125
angle_deg_per_lsb: 0.001
speed_deg_per_sec_per_lsb: 0.1
motor_encoder_counts_per_rev: 65536
joint_offsets:
- 0.02462659574563998
- 0.037472219040318264
- -4.1800635585264185
- 4.264799293710743
- -2.079280551070924
- -0.4788572602234245
- -2.7390848214948624
- -1.7537940988665024
imu_offsets:
- 1.0
- 0.0
- 0.0
- 0.0
