joint_names:
- hip_L_Joint
- hip_R_Joint
- thigh_L_Joint
- thigh_R_Joint
- knee_L_Joint
- knee_R_Joint
- wheel_L_Joint
- wheel_R_Joint
joint_indices:
- 0
- 1
- 2
- 3
- 4
- 5
wheel_indices:
- 6
- 7
num_joints: 8
can_channels:
- can0
- can1
motor_bus_index:
- 0
- 1
- 0
- 1
- 0
- 1
- 0
- 1
motor_node_ids:
- 1
- 2
- 3
- 4
- 5
- 6
- 7
- 8
motor_torque_constant_nm_per_amp:
- 0.26182
- 0.26182
- 0.26182
- 0.26182
- 0.26182
- 0.26182
- 0.24691
- 0.24691
motor_gear_ratio:
- 1
- 1
- 1
- 1
- 2
- 2
- 1
- 1
motor_direction:
- 1
- 1
- 1
- 1
- 1
- 1
- 1
- 1
wheel_radius: 0.095
num_traj_points: 200
nsc_urdf_path: null
nsc_leg_proportional_gain:
- 10.0
- 10.0
- 10.0
- 10.0
- 10.0
- 10.0
- 0.0
- 0.0
nsc_leg_derivative_gain:
- 1.0
- 1.0
- 1.0
- 1.0
- 1.0
- 1.0
- 0.0
- 0.0
nsc_wheel_outer_proportional_gain: 0.1
nsc_wheel_outer_derivative_gain: 0.05
nsc_wheel_inner_proportional_gain: 3.0
nsc_wheel_inner_derivative_gain: 0.1
nsc_theta_cmd_limit: 10.0
policy_mode: movable
policy_checkpoint_path: src/goat_control/checkpoint/stand.onnx
policy_device: cpu
policy_command_vx_limit: 0.1
policy_command_wz_limit: 0.1
policy_command_height_lower_limit: 0.39
policy_command_height_upper_limit: 0.56
policy_command_vx_step: 0.01
policy_command_wz_step: 0.01
policy_command_height_step: 0.02
policy_command_joint_step: 10.0
policy_decimation: 2.0
policy_leg_proportional_gain:
- 3.0
- 3.0
- 3.0
- 3.0
- 3.0
- 3.0
policy_leg_derivative_gain:
- 0.1
- 0.1
- 0.1
- 0.1
- 0.1
- 0.1
policy_wheel_proportional_gain:
- 0.05
- 0.05
policy_fixed:
  observation_info:
    joint_pos: 6
    joint_vel: 6
    previous_action: 6
    joint_command: 6
  action_scale_factor:
  - 0.5
  - 0.5
  - 0.5
  - 0.5
  - 0.5
  - 0.5
  natural_joint_position:
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  effective_joint_indices:
  - 0
  - 1
  - 2
  - 3
  - 4
  - 5
  effective_wheel_indices:
  - 6
  - 7
policy_movable:
  observation_info:
    base_ang_vel: 3
    gravity_vector: 3
    base_command: 4
    joint_pos: 4
    joint_vel: 6
    previous_action: 6
  action_scale_factor:
  - 0.5
  - 0.5
  - 0.5
  - 0.5
  - 5.0
  - 5.0
  natural_joint_position:
  - 0.0
  - 0.0
  - 0.9756
  - -0.9756
  - 2.0944
  - -2.0944
  - 0.0
  - 0.0
  effective_joint_indices:
  - 2
  - 3
  - 4
  - 5
  effective_wheel_indices:
  - 6
  - 7
max_torque_per_joint:
- 0.0
- 0.0
- 4.5
- 4.5
- 9.0
- 9.0
- 2.5
- 2.5
joint_pos_limit:
- -1.22173
- 0.750492
- -0.750492
- 1.22173
- -0.261799
- 2.05949
- -2.05949
- 0.261799
- -0.262
- 2.2253
- -2.2253
- 0.262
- -.inf
- .inf
- -.inf
- .inf
joint_pos_soft_limit_coeff: 0.95
joint_vel_estop_threshold: 5.0
joint_vel_estop_sample_num: 10
motor_current_amp_per_lsb: 0.01611328125
angle_deg_per_lsb: 0.001
speed_deg_per_sec_per_lsb: 0.1
motor_encoder_counts_per_rev: 65536
max_current_lsb: 2048
joint_offsets:
- -4.1816692614382545
- -4.144371575323135
- -4.168893451313657
- 6.290590739195799
- 6.580179259345202
- -2.0211174537482135
- -2.828253692979252
- 2.513047230069076
imu_offsets:
- 1.0
- 0.0
- 0.0
- 0.0
