robot:
  joint_names: ["j0","j1","j2","j3","j4","j5","wheel_l","wheel_r"]
  joint_indices: [0,1,2,3,4,5]
  wheel_indices: [6,7]
  knee_indices: [2,5]

  motor_torque_constant_nm_per_amp: [0.12,0.12,0.12,0.12,0.12,0.12,0.08,0.08]
  motor_gear_ratio: [50,50,50,50,50,50,10,10]
  motor_direction: [1,1,1,1,1,1,1,-1]

pd:
  proportional_gain: [40,40,40,40,40,40,0,0]
  derivative_gain:   [2,2,2,2,2,2,0,0]

wheel_pi:
  proportional_gain: [0,0,0,0,0,0,1.5,1.5]
  integral_gain:     [0,0,0,0,0,0,0.5,0.5]
  integrator_state_limit: 0.7
  output_limit_per_joint: [999,999,999,999,999,999,3,3]

safety:
  torque_lpf_alpha_per_joint: [0.6,0.6,0.6,0.6,0.6,0.6,0.8,0.8]
  max_torque_per_joint: [10,10,10,10,10,10,3,3]

estimation:
  motor_current_amp_per_lsb: 0.01611328125
  angle_deg_per_lsb: 0.001
  speed_deg_per_sec_per_lsb: 1.0
